### ISSUE TITLE
[Addition Request]: PHP, Laravel, React, SvelteKit, Gleam, Nix

### ISSUE THREAD

**Issue by ghost** [Nighty3098/DevIcons#1]
Love these icons!
It would be amazing to have the above mentioned added to this aswell.

**Comment by Nighty3098** [comment]
<h3>Hello. I'm glad you like my icons.</h3>

The icons you suggested have been added to the project :)

<div align="center">
  <img src="https://github.com/Nighty3098/DevIcons/blob/main/badges/badges_nix.png?raw=true" width="15%" />
  <img src="https://github.com/Nighty3098/DevIcons/blob/main/badges/badges_gleam.png?raw=true" width="15%" />
  <img src="https://github.com/Nighty3098/DevIcons/blob/main/badges/badges_php.png?raw=true" width="15%" />
  <img src="https://github.com/Nighty3098/DevIcons/blob/main/badges/badges_laravel.png?raw=true" width="15%" />
  <img src="https://github.com/Nighty3098/DevIcons/blob/main/badges/badges_svelte.png?raw=true" width="15%" />
  <img src="https://github.com/Nighty3098/DevIcons/blob/main/badges/badges_react.png?raw=true" width="15%" />
</div>

`Sorry for the delay`

**Comment by ghost** [comment]
@Nighty3098 
Thank you so much they look amazing!!!

**Comment by ghost** [comment]
As a thank you I wrote up a quick article on my blog, hope we can get many more to appreciate these awesome icons!
https://dev.to/jasper-at-windswept/the-cleanest-icons-for-your-next-readme-1f0h
