### ISSUE TITLE
[Addition Request]: Java, Golang, Supabase, Firebase, Pocketbase

### ISSUE THREAD

**Issue by ghost** [Nighty3098/DevIcons#2]
Hey Nightly,
Love what you have been doing with the icons so far!
If you get a chance could we add these ones to the collection?

**Comment by Nighty3098** [comment]
Hello. I will try to add them as soon as possible.

**Comment by Nighty3098** [comment]
<br>
<div align="center">
<h1>Icons have been added to the project : )</h1>
<br><br><br>
<img src="https://github.com/Nighty3098/DevIcons/blob/main/badges/badges_java.png?raw=true" width="80px" />
<img src="https://github.com/Nighty3098/DevIcons/blob/main/badges/badges_golang.png?raw=true" width="80px" />
<img src="https://github.com/Nighty3098/DevIcons/blob/main/badges/badges_supabase.png?raw=true" width="80px" />
<img src="https://github.com/Nighty3098/DevIcons/blob/main/badges/badges_firebase.png?raw=true" width="80px" />
<img src="https://github.com/Nighty3098/DevIcons/blob/main/badges/badges_pocketbase.png?raw=true" width="80px" />
<br><br>
<h3>If you have any suggestions for changing the icons, email me</h3>
</div>
<br>

**Comment by ghost** [comment]
@Nighty3098 
Thanks so much, if I could make one slight suggestion do you think the background color for Supabase could be a shade of green?
Would make much more sense branding-wise.

**Comment by Nighty3098** [comment]
<div align="center">

## It's done

<br>
<img src="https://github.com/Nighty3098/DevIcons/blob/main/badges/badges_supabase.png?raw=true" width="80px" />

</div>
