### ISSUE TITLE
 [Addition Request]: Socials: LinkedIn, Dev.to, Matrix, YouTube

### ISSUE THREAD

**Issue by ghost** [Nighty3098/DevIcons#3]
Hey @Nighty3098 
I'm working on my personal portfolio and I would love to see these new icons made available.
They are just so clean and professional, perfect for the aesthetic I'm going for.
Thanks as always!

**Comment by Nighty3098** [comment]
<div align="center">
<br><br>
<h1>Hi 👋🏻 </h1>
<br>🚀<br><br>
<img src="https://github.com/Nighty3098/DevIcons/blob/main/badges/badges_dev.png?raw=true" width="60px" />
<img src="https://github.com/Nighty3098/DevIcons/blob/main/badges/badges_youtube.png?raw=true" width="60px" />
<img src="https://github.com/Nighty3098/DevIcons/blob/main/badges/badges_linkedIn.png?raw=true" width="60px" />
<img src="https://github.com/Nighty3098/DevIcons/blob/main/badges/badges_matrix.png?raw=true" width="60px" />
</div>
